---
language: python
cache: pip

env:
  - MOLECULE_DISTRO=debian10
  - MOLECULE_DISTRO=debian9
  - MOLECULE_DISTRO=ubuntu1804
  - MOLECULE_DISTRO=ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule docker ansible-lint yamllint

script:
  - molecule test -s docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
