---

- name: ensure etherpad user is present
  user:
    name: "{{ etherpad_user }}"
    home: "{{ etherpad_home }}"
    shell: "/bin/bash"
    state: present

- name: ensure required packages are installed
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ etherpad_required_packages }}"

- name: allow overcommiting of memory
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    sysctl_path: /etc/sysctl.d/90-ansible-vm.conf
    sysctl_set: yes

- name: ensure etherpad is latest
  git:
    repo: "{{ etherpad_repository }}"
    dest: "{{ etherpad_path }}"
    version: "{{ etherpad_repository_version}}"
    key_file: "{{ etherpad_repository_key_file}}"
  become: true
  become_user: "{{ etherpad_user }}"
  register: repository

- name: ensure etherpad config is latest
  template:
    src: settings.json.j2
    dest: "{{ etherpad_path }}/settings.json"
    owner: "{{ etherpad_user }}"
    group: "{{ etherpad_group }}"
    mode: 0644
  become: true
  become_user: "{{ etherpad_user }}"
  notify: restart etherpad-lite

- name: ensure redis module for nodejs is present
  npm:
    name: redis
    path: "{{ etherpad_path }}"
    state: present
  become: true
  become_user: "{{ etherpad_user }}"
  when: "etherpad_db_type == 'redis'"

- name: ensure etherpad dependencies are latest
  command: bin/installDeps.sh
  args:
    chdir: "{{ etherpad_path }}"
  become: true
  become_user: "{{ etherpad_user }}"
  when: repository.changed

- name: ensure etherpad systemd unit is latest
  template:
    src: etherpad-lite.service.j2
    dest: /etc/systemd/system/etherpad-lite.service
    owner: root
    group: root
    mode: 0644
  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 14)

- name: ensure etherpad sysvinit script is latest
  template:
    src: etherpad-lite.sysvinit.j2
    dest: /etc/init.d/etherpad-lite
    owner: root
    group: root
    mode: 0755
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 14)

- name: ensure etherpad will start after system is booted
  service:
    name: etherpad-lite
    enabled: yes

- name: ensure etherpad api key is latest
  template:
    src: APIKEY.txt.j2
    dest: "{{ etherpad_path }}/APIKEY.txt"
    owner: "{{ etherpad_user }}"
    group: "{{ etherpad_group }}"
    mode: 0640
  become: true
  become_user: "{{ etherpad_user }}"
  notify: restart etherpad-lite

- name: install etherpad plugins
  npm:
    name: "{{ item }}"
    path: "{{ etherpad_path }}"
    state: present
  become: true
  become_user: "{{ etherpad_user }}"
  with_items: "{{ etherpad_plugins|d() }}"

- name: ensure ep_hide_referrer patch is applied
  patch:
    src: "ep_hide_referrer/index.js.patch"
    dest: "{{ etherpad_path }}/node_modules/ep_hide_referrer/static/js/index.js"
    backup: yes
  become: true
  become_user: "{{ etherpad_user }}"
  when: etherpad_plugins|intersect('ep_hide_referrer')|length > 0
  notify: restart etherpad-lite

- include: console.yml
  when: etherpad_console_enabled

- include: monit.yml
  when: etherpad_monit_enabled
