---
- name: ensure python-mysqldb is installed
  apt:
    pkg: python-mysqldb
    state: present

- name: ensure mysql database is present
  mysql_db:
    name: "{{ etherpad_mysql_database_name }}"
    collation: "{{ etherpad_mysql_database_collation }}"
    state: present
    login_user: root
    login_password: "{{ etherpad_mysql_root_password|default(omit) }}"
  register: database

- name: ensure mysql schema is present
  template:
    src: schema.sql.j2
    dest: /tmp/etherpad_schema.sql
  when: database.changed

- name: ensure mysql database is present
  mysql_db:
    name: "{{ etherpad_mysql_database_name }}"
    collation: "{{ etherpad_mysql_database_collation }}"
    state: import
    target: /tmp/etherpad_schema.sql
    login_user: root
    login_password: "{{ etherpad_mysql_root_password|default(omit) }}"
  when: database.changed

- name: ensure database schema is absent after import
  file:
    path: /tmp/etherpad_schema.sql
    state: absent
  when: database.changed

- fail:
    msg: "You need to set a password for mysql user!"
  when: etherpad_mysql_database_password is undefined or etherpad_mysql_database_password == ""

- name: ensure mysql user is present
  mysql_user:
    name: "{{ etherpad_mysql_database_user }}"
    state: present
    password: "{{ etherpad_mysql_database_password }}"
    priv: "{{ etherpad_mysql_database_user }}.*:ALL"
    login_user: root
    login_password: "{{ etherpad_mysql_root_password|default(omit) }}"
