---
- name: restart etherpad-lite
  service:
    name: etherpad-lite
    state: restarted

- name: restart monit
  service:
    name: monit
    state: restarted

- name: ensure etherpad dependencies are latest
  command: bin/installDeps.sh
  args:
    chdir: "{{ etherpad_path }}"
  become: true
  become_user: "{{ etherpad_user }}"
  notify: restart etherpad-lite
