---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: stretch64
    box: debian/stretch64
  - name: jessie64
    box: debian/jessie64
provisioner:
  name: ansible
  become: true
lint: yamllint .
